version: 2.1

workflows:
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "Docker Hub"

commands:
  setup-multi-arch-docker:
    steps:
      - run:
          name: Prepare for multi arch build (setup qemu)
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-arm-static --version
            qemu-aarch64-static --version
            update-binfmts --version
      - run:
          name: Create multi arch docker image builder
          command: |
            docker buildx create --name multi-arch-builder
            docker buildx use multi-arch-builder
            docker buildx inspect --bootstrap

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - setup-multi-arch-docker
      - checkout
      - run:
          name: Build and push image
          no_output_timeout: 1h
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            VERSION="${CIRCLE_TAG}" PUSH=true ./build.sh
